// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ozA6bGMKz4QnQ0NkPdDaUrhrGcTc1BA',
    appId: '1:880596154626:web:738cd8a94c4404920fea1b',
    messagingSenderId: '880596154626',
    projectId: 'tours-yucatan',
    authDomain: 'tours-yucatan.firebaseapp.com',
    storageBucket: 'tours-yucatan.appspot.com',
    measurementId: 'G-MTMN4Y0PMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8V9NjN6zOtlSFOJoOzvYOF5bMw42u2Co',
    appId: '1:880596154626:android:1e3da2a12f2d47b50fea1b',
    messagingSenderId: '880596154626',
    projectId: 'tours-yucatan',
    storageBucket: 'tours-yucatan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACaNi7Lrgr02VJ1XlwoZWWZLBB3vWcKWw',
    appId: '1:880596154626:ios:2afe1e51413df75a0fea1b',
    messagingSenderId: '880596154626',
    projectId: 'tours-yucatan',
    storageBucket: 'tours-yucatan.appspot.com',
    iosClientId: '880596154626-lmbdqcbetovadd48fc9f11eod0h87nkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoToursYucatan',
  );
}
